# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html

# Site
title: 牢丰的博客
subtitle: 记录学习点滴
description: 编程笔记
author: 牢丰
language: zh-CN
timezone: ''

# URL
url: https://lee123id.github.io/MyBlog/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

# 主题配置
theme: landscape

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

# Pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
include:
exclude:
ignore:

# Deployment
deploy:
  type: git
  repo: https://github.com/lee123id/MyBlog.git
  branch: gh-pages
  message: "更新博客内容 - {{ now('YYYY-MM-DD HH:mm:ss') }}"