name: Deploy Hexo Blog

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install Hexo and dependencies
      run: |
        npm install -g hexo-cli
        npm install
        
    - name: Ensure theme directory
      run: |
        # 创建主题目录并复制文件
        mkdir -p themes/landscape
        cp -R node_modules/hexo-theme-landscape/* themes/landscape/
        
    - name: Build site with Hexo
      run: |
        hexo clean
        hexo generate
        
    - name: Add .nojekyll file
      run: touch ./public/.nojekyll
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages
        force_orphan: true
        full_commit_message: "Deploy: ${{ github.sha }}"